import Head from "next/head";
import { useState } from "react";

import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [showDynamicImage, setShowDynamicImage] = useState(false);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={inter.className}>
        <button onClick={() => setShowDynamicImage((state) => !state)}>
          Toggle Dynamic Image
        </button>
        <br />
        <br />
        <img
          src="/image1.png"
          alt="ssr-image"
          width={280}
          height={180}
          onLoadStart={() => console.log("Loading Image...")}
          onLoad={() => console.log("Image Loaded")}
        />
        <p>SSR Image</p>
        <br />
        <br />
        {showDynamicImage ? (
          <>
            <img
              src="/image1.png"
              alt="dynamic-image"
              width={280}
              height={180}
              onLoadStart={() => console.log("Loading Dynamic Image...")}
              onLoad={() => console.log("Dynamic Image Loaded")}
            />
            <p>Dynamic Image</p>
          </>
        ) : null}
      </main>
    </>
  );
}
